### ISSUE TITLE
Is this for paid users only or will it work for the freeplan also?

### ISSUE THREAD

**Issue by BobWs** [shenxn/protonmail-bridge-docker#15]
Hi I was wondering if this is for the paid version only or will it also work for the Protonmail  freeplan?
And does it support multiple accounts?

**Comment by shenxn** [comment]
The container packs the official bridge, so it only works with paid accounts. And yes, it does support multiple accounts. Just log in multiple times at the initialization step.

**Comment by BobWs** [comment]
Thanks for sharing! It’s a pity it will only work with the paid version, I have the freeplan...
