### ISSUE TITLE
Docker container on Synology works at start, but seems to hang after a while...

### ISSUE THREAD

**Issue by OrpheeGT** [shenxn/protonmail-bridge-docker#22]
Hello,

I applied the configuration and it works well just after the container start, but after a while, I can't send test mail from Synology any more.
If I stop/start the container, it works again for a while, but again, stop working after sometime...

![image](https://user-images.githubusercontent.com/8038551/104172926-4db1ce00-5405-11eb-9e6d-12660474151b.png)

![image](https://user-images.githubusercontent.com/8038551/104172950-599d9000-5405-11eb-8088-7fe47152780c.png)

![image](https://user-images.githubusercontent.com/8038551/104172992-67ebac00-5405-11eb-86b9-8e650b31e150.png)

When it does not work anymore, I don't have any error message from Synology, it says the test mail have been sent, but nothing.

Usually when it works, there is a little time, like 3/5 seconds before Synology pops the message has been sent.
When it doesn't work anymore, the message pops quite fast, 1 second...

I don't have any log to share... It seems docker container don't trace any logs, and from Synology as it says mail sent...

**Comment by OrpheeGT** [comment]
Hi again, it seems to be more a Synology issue, I tried from my computer with my LAN IP and it worked.. The the container is not hanged...

**Comment by OrpheeGT** [comment]
I closed the ticket myself so I don't know if the following comment will be read but : 

May I suggest to add some security as an option for those like me who want the container only accessible from localhost ? :

docker run -d --name=protonmail-bridge -v protonmail:/root -p 127.0.0.1:1025:25/tcp -p 127.0.0.1:1143:143/tcp --restart=unless-stopped shenxn/protonmail-bridge

Thanks

**Comment by shenxn** [comment]
@OrpheeGT Thanks for the advice. I'll add that to README.
