### ISSUE TITLE
Helm chart for protonmail-bridge-docker

### ISSUE THREAD

**Issue by Eagleman7** [shenxn/protonmail-bridge-docker#23]
Hello!

I've used your container to setup an helm chart app for kubernetes:
https://github.com/k8s-at-home/charts/tree/master/charts/protonmail-bridge

This will provide an easier way to run your app in kubernetes since it can be installed with 2 command:

helm repo add k8s-at-home https://k8s-at-home.com/charts/
helm install k8s-at-home/protonmail-bridge

Then the desciption from the kubernetes ticket still applies:

1. Get the name of your deployed pod kubectl get pods
2. Run interactively on the pod (setup only) kubectl exec --stdin --tty protonmail-bridge-deployment-6c79fd7f84-ftwcw -- /bin/bash
3. Once logged in, execute the init command bash /protonmail/entrypoint.sh init
4. You should now see the CLI for protonmail-bridge, authenticate with login
5. (optional) if you're like me and use split address mode, change mode and info are good for printing the details.
6. Copy your SMTP server info (or IMAP, your choice)
7. delete the active pod so a new one gets created (which will properly fire up with your persisted settings)

**Comment by shenxn** [comment]
Thanks for the contribution. I already updated README to metion the helm chart and this issue.

**Comment by Eagleman7** [comment]
Get the name of your deployed pod `kubectl get pods`
Run interactively on the pod (setup only) `kubectl exec --stdin --tty -n core protonmail-bridge-deployment-6c79fd7f84-ftwcw -- /bin/bash`
`chmod +x /protonmail/entrypoint.sh init`
`kill 19`
Once logged in, execute the init command bash `/protonmail/entrypoint.sh init`
You should now see the CLI for protonmail-bridge, authenticate with `login`
(optional) if you're like me and use split address mode, change mode and info are good for printing the details.
Copy your SMTP server info (or IMAP, your choice)
delete the active pod so a new one gets created (which will properly fire up with your persisted settings)
