### ISSUE TITLE
Error: Expected response code 250 but got code "451", with message "451 4.0.0 backend: invalid return path: not owned by user "

### ISSUE THREAD

**Issue by MagicTrevor** [shenxn/protonmail-bridge-docker#28]
I have this set in a different docker container and part of the bridge network which is different from another container I am trying to connect to it. I have only exposed port 25.

User gets added successfully in bridge.

I get the following error:
```
Error: Expected response code 250 but got code "451", with message "451 4.0.0 backend: invalid return path: not owned by user "
```

**Comment by shenxn** [comment]
Sorry but I have no idea what this message means. Where do you get this log? From the bridge container or the SMTP client?

**Comment by MagicTrevor** [comment]
Closing. I was trying to get this to work with nextcloud in another container and nextcloud was giving me that error. Turns out the 'From' email needs to actually exist in Protonmail for it to work.

**Comment by Kybeer** [comment]
> 
> 
> Closing. I was trying to get this to work with nextcloud in another container and nextcloud was giving me that error. Turns out the 'From' email needs to actually exist in Protonmail for it to work.

Thanks for this finding. I got exactly the same issue to start with.

**Comment by plind-dm** [comment]
How is it resolved?

**Comment by GordonFreemanK** [comment]
> Closing. I was trying to get this to work with nextcloud in another container and nextcloud was giving me that error. Turns out the 'From' email needs to actually exist in Protonmail for it to work.

That's very useful info, thanks
@plind-dm the "From" field you're sending your email with needs to exist, at least if it's a Proton email.
