### ISSUE TITLE
Running build produces no matching manifest

### ISSUE THREAD

**Issue by ncc0624** [shenxn/protonmail-bridge-docker#46]
pi@wolf359:~ $ sudo docker run --rm -it -v protonmail:/root shenxn/protonmail-bridge:build init
Unable to find image 'shenxn/protonmail-bridge:build' locally
build: Pulling from shenxn/protonmail-bridge
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
pi@wolf359:~ $

**Comment by shenxn** [comment]
It should be fixed by #45.
