### ISSUE TITLE
Running on Synology NAS with SSL for SMTP instead of STARTTLS

### ISSUE THREAD

**Issue by JVT038** [shenxn/protonmail-bridge-docker#48]
Hi,
I want to use SSL instead of STARTTLS for SMTP, and for some reason my Synology NAS can't connect with the Protonmail bridge server. 
When I use STARTTLS, it works fine, but when I use SSL it doesn't. 
It says "Test mail failed to send. Please check your settings and try again".
These are my settings:
![image](https://user-images.githubusercontent.com/47184046/155724385-599b40aa-be94-409a-8e87-4a05ef4d8f60.png)

**Comment by shenxn** [comment]
It is either because SSL/TLS is simply not supported by the bridge, or your NAS does not trust the self-signed certificate that the bridge provides. I think there is no easy way around it.
