### ISSUE TITLE
Only use it as SMTP relay/send

### ISSUE THREAD

**Issue by OrpheeGT** [shenxn/protonmail-bridge-docker#49]
Hello,

I'm using it on my Synology NAS to be able to send notification mails using Protonmail.
but the volume folder is quite heavy

`# ls -la
drwx------    1 root     root            20 Mar  4 14:09 .cache
drwx------    1 root     root            38 Mar  4 14:09 .config
drwx------    1 root     root           280 Mar  4 14:11 .gnupg
drwx------    1 root     root            58 Mar  4 14:09 .password-store
# du -shc
1016.9M .
1016.9M total
# cd .config/protonmail/bridge/cache/c11/messages/
# du -shc
1014.2M .
1014.2M total`

would it be possible to avoid cache building ?

Thanks

**Comment by shenxn** [comment]
I don't think it is possible unless the bridge itself supports that. There is nothing I can do here. Closing it now. Feel free to reopen if the bridge itself got support for it.

**Comment by OrpheeGT** [comment]
Hello @shenxn 

May I ask your opinion about this ?:

https://github.com/ProtonMail/proton-bridge/search?q=cache_enabled

not usable ?

Thank you

**Comment by shenxn** [comment]
> Hello @shenxn
> 
> May I ask your opinion about this ?:
> 
> https://github.com/ProtonMail/proton-bridge/search?q=cache_enabled
> 
> not usable ?
> 
> Thank you

Theoretically this can work, but it requires changing the way we configure the bridge. Currently it entirely relies on the commands provided by the cli, maybe we can consider changing the perfs file directly as well.
