### ISSUE TITLE
Combined or split mode

### ISSUE THREAD

**Issue by leon1995** [shenxn/protonmail-bridge-docker#5]
Hi,

is there a way to choose from which address I can send an email?
Is there a way to set up the split mode for this bridge?

Thanks!

**Comment by ghudgins** [comment]
yes - after logging in enter

`change mode`

then you can `info` to see the split

**Comment by shenxn** [comment]
Yes. This image is just a packing of the official cli. For more information on how to use the cli, you can reference the official guide https://protonmail.com/support/knowledge-base/bridge-cli-guide/.
