### ISSUE TITLE
docker init exits prematurely

### ISSUE THREAD

**Issue by Neshura87** [shenxn/protonmail-bridge-docker#60]
Running Ubuntu 20.04 on a Raspberry Pi 4 therefore I'm using the build version.
When executing `docker run --rm -it -v protonmail:/root shenxn/protonmail-bridge:build init` I get the following:
```
+ [[ init == init ]]
+ gpg --generate-key --batch /protonmail/gpgparams
gpg: Generating a basic OpenPGP key
gpg: key 5D55B2B57D8133D9 marked as ultimately trusted
gpg: revocation certificate stored as '/root/.gnupg/openpgp-revocs.d/0700EEC6A8E54E1FD5E87DFE5D55B2B57D8133D9.rev'
gpg: done
+ pass init pass-key
Password store initialized for pass-key
+ pkill protonmail-bridge
```
Is there possibly some dependency I'm missing?

**Comment by Neshura87** [comment]
Pass install was borked, fixed it

**Comment by azoller1** [comment]
How did you fix this? I have the same issue.

@Neshura87
