### ISSUE TITLE
Pkill causes container to exit

### ISSUE THREAD

**Issue by jcrsilva** [shenxn/protonmail-bridge-docker#63]
The [entrypoint script](https://github.com/shenxn/protonmail-bridge-docker/blob/master/build/entrypoint.sh) had the following line added in commit `680e82076e9313c94330bcccac745db07468854c`:

```bash
pkill protonmail-bridge
```

I don't know why this is even here since in normal conditions you won't be able to have two bridge instances. When running in kubernetes the correct way to do the init process would be with an init container before the main one starts up.

This being said when another process does not exist this command will exit with rc 1:

> Exit Status
> The following exit values are returned:
> 0 One or more processes were matched.
> 1 No processes were matched.
> 2 Invalid command line options were specified.
> 3 A fatal error occurred.

Since at the top of the script we're doing:

```bash
set -ex
```

This will cause the container to exit immediately if another instance of the bridge does not exist.

IMO the whole `pkill` line should be removed since at first glance it looks like an antipattern, however if it is decided to keep it it should be modified to always return `0`:

```bash
pkill protonmail-bridge || true
```

**Comment by shenxn** [comment]
Yes, I agree this is not a good practice. I think the whole point of this command is to allow users run init through entrypoint later, after the container started. And the reason behind this is that it is impossible to run and attach to a container at the same time in k8s. Maybe, a better practice is to provide them a new command / script for k8s users. But anyways, I'll fix this issue.

**Comment by shenxn** [comment]
Should be fixed by https://github.com/shenxn/protonmail-bridge-docker/commit/0fa5f9fc1339be128661736d0d3f542bab7b3289
