### ISSUE TITLE
Is this bridge for only paid accounts?

### ISSUE THREAD

**Issue by BobWs** [shenxn/protonmail-bridge-docker#67]
Hi,
Will this work with only the paid accounts or also the free?
I don’t have any paid ProtonMail accounts just the free version, and was looking for a solution to combine two different free accounts into one mail app / mailbox.
TIA

**Comment by danhayden** [comment]
Yes you need a paid proton account to use proton bridge as stated on https://proton.me/mail/bridge Proton Mail Bridge is currently available for paid subscribers.
