### ISSUE TITLE
init failed on raspberry pi 4

### ISSUE THREAD

**Issue by andrasbakos** [shenxn/protonmail-bridge-docker#7]
The following init command failed on raspberry pi 4.

```
root@host01:/home/pi# docker run --rm -it -v protonmail:/root shenxn/protonmail-bridge:build init
+ [[ init == init ]]

+ gpg --generate-key --batch /protonmail/gpgparams
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: Generating a basic OpenPGP key
gpg: can't connect to the agent: IPC connect call failed
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
gpg: done

root@host01:/home/pi# uname -a
Linux host01 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
```

Please advise.

**Comment by tml89** [comment]
On raspberry pi 3 same issue

`Linux home 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux`

**Comment by shenxn** [comment]
Are you using Raspbian or any other system? Also, what is the version of your operating system?

**Comment by andrasbakos** [comment]
Here you go.

```
lsb_release -a

No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by shenxn** [comment]
Thanks. Currently I don't have access to a Raspberry Pi. I'll be back home in around 10 days and I'll do some tests and try to fix this.

**Comment by tml89** [comment]
Here you go.
`lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
`

**Comment by shenxn** [comment]
@andrasbakos @tml89 Can you try the image tagged with `build-dev`? If that works, I'll merge the fix into the main branch.

**Comment by andrasbakos** [comment]
Initialization, smtp and imap all work great! Thank you.

**Comment by dnordgren** [comment]
I had this same issue and `build-dev` fixed init for me as well. Thank you for the fix and all your work on this project!

**Comment by shenxn** [comment]
Merged. Now the `:build` image should work as well.
