### ISSUE TITLE
Accessing bridge-cli from Portainer

### ISSUE THREAD

**Issue by TheFockinFury** [shenxn/protonmail-bridge-docker#77]
Hi folks, I'm trying to access the bridge-cli to get my connection settings, update my connection, etc. 

To do so, I'm going in through the console feature in Portainer using /bin/bash as the shell. 

I can't find this documented and I'm sure I'm just missing something, but how could I access bridge-cli from within the terminal for the protonmail-bridge container? So far it's not recognizing any command I can think of and there has to be a way to confirm info without having to destroy the container and re-run the init / login process... is there?

**Comment by eyduh** [comment]
You would need to run `/protonmail/bridge --cli` or `/protonmail/proton-bridge --cli` however when I do I get dbus errors, presumably because cli prompt is already running.

**Comment by vleeuwenmenno** [comment]
Then how are you supposed to log in at all? I am trying this with docker-compose, but am unable to login because I have no idea how.

**Comment by FriedCheese2006** [comment]
Ran into the same problem with the compose running in Portainer. What I did:

1. `top` to get the PID for 'bridge' and 'protonmail-brid'
2. `kill` for each PID
3. `which` for 'protonmail-bridge' command location (was in /usr/bin)
4. `/usr/bin/protonmail-bridge --cli' to get started
5. Ran the `login` command and followed the prompts.
