### ISSUE TITLE
Running on Synology NAS

### ISSUE THREAD

**Issue by reggian** [shenxn/protonmail-bridge-docker#8]
Hi, I am trying to setup ProtonMail Bridge on Synology NAS and a docker container looks like the best bet.
However when I install it I receive an error:

>ProtonMail Bridge is not able to detect a supported password manager (pass, gnome-keyring). Please install and set up a supported password manager and restart the application.

I am fairly new to docker.
As I understand it all dependencies should be contained within the container so I am asking for help on how to get the said password manager included in the container.

Please let me know if I can provide additional info.
Any help would be greatly appreciated.

**Comment by shenxn** [comment]
You need to run the [initialization command](https://github.com/shenxn/protonmail-bridge-docker#initialization) to initialize the password manager. You may need to SSH into your NAS to run that command. I'm not sure if there is any way to do that in the web-based UI.

**Comment by reggian** [comment]
That worked, my apologies.
I had to SSH into the NAS and run it from there.
Thanks for your gelp.
