### ISSUE TITLE
Container with "build"-tag wont launch - error=exit status 1

### ISSUE THREAD

**Issue by Hannes1909** [shenxn/protonmail-bridge-docker#81]
Hi,

i get the following error when launching the container with the build-tag:
```
INFO[Mar  5 21:19:08.509] No more updates found, looking up bridge executable  error="no available newer versions" exe_to_launch=bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git
/protonmail/bridge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /protonmail/bridge)
/protonmail/bridge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /protonmail/bridge)
FATA[Mar  5 21:19:08.522] Failed to launch                              error="exit status 1" exe_path=/protonmail/bridge exe_to_launch=bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git
```

Launching with `docker run --rm -it -v protonmail:/root shenxn/protonmail-bridge:build init` - as per #79 the deb version is (from my understanding) not yet updated to jammy.
Running docker on Arch Linux, latest version, also tried on Debian 11. Any hints appreciated :)

**Comment by richburdon** [comment]
Same issue, but different error:

```
2023-03-24 13:38:19 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
2023-03-24 13:38:19 FATA[Mar 24 17:38:19.761] Failed to launch                              error="exit status 255" exe_path=/root/.cache/protonmail/bridge/updates/3.0.21/proton-bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git
```

Apple M1 Silicon (arm64).
2.4.0-build works (per https://github.com/shenxn/protonmail-bridge-docker/issues/74) but won't allow SSL config for IMAP so was trying the latest build.

**Comment by OGrigorios** [comment]
Hello, I am facing a similar issue.
Running this under Debian 11 with an up-to-date docker install yields the following error:
`INFO[Apr 12 14:57:58.569] No more updates found, looking up bridge executable  error="no available newer versions" exe_to_launch=bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git
/protonmail/bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /protonmail/bridge)
/protonmail/bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /protonmail/bridge)
FATA[Apr 12 14:57:58.574] Failed to launch                              error="exit status 1" exe_path=/protonmail/bridge exe_to_launch=bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git`

**Comment by PseudoMortus** [comment]
I had this same error around the time the update happened on Proton's end was keeping tabs on it during this time. I just tried it again, and (though this might have been due to me re-doing my system to some degree) it worked as of today (Sunday May 28th 10:30PM CST). Can one of you three try again and see if this remains an issue for you?

**Comment by BortEngineerDude** [comment]
@PseudoMortus
Trying to run image on Armbian/rockpi4c today (Jun 9 2023) ends with the same result as @OGrigorios got [here](https://github.com/shenxn/protonmail-bridge-docker/issues/81#issuecomment-1505429321)

```
docker run --rm -it -v protonmail:/root shenxn/protonmail-bridge:build init
+ [[ init == init ]]
+ gpg --generate-key --batch /protonmail/gpgparams
gpg: Generating a basic OpenPGP key
gpg: key 4618740700715AF0 marked as ultimately trusted
gpg: revocation certificate stored as '/root/.gnupg/openpgp-revocs.d/0C1AAA56D5FD823894C9DABC4618740700715AF0.rev'
gpg: done
+ pass init pass-key
Password store initialized for pass-key
+ pkill protonmail-bridge
+ true
+ /protonmail/proton-bridge --cli init
INFO[Jun  9 08:51:32.740] No more updates found, looking up bridge executable  error="no available newer versions" exe_to_launch=bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git
/protonmail/bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /protonmail/bridge)
/protonmail/bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /protonmail/bridge)
FATA[Jun  9 08:51:32.746] Failed to launch                              error="exit status 1" exe_path=/protonmail/bridge exe_to_launch=bridge launcher_path=/protonmail/proton-bridge launcher_version=2.4.8+git
```

**Comment by Hannes1909** [comment]
sorry i lost track on this issue :(
but everything seems to work fine now with the latest build :)
