### ISSUE TITLE
only able to send one mail, then need to restart proton-bridge

### ISSUE THREAD

**Issue by bahrthaare** [shenxn/protonmail-bridge-docker#88]
hi, had set up the proton-bridge and I'm able to send one mail, after this mail I'm not able to send a next one. I need to kill proton-bride and start again in the docker or restart the whole docker to send one mail again. I don't know were I can see what the issue is. May some one can help me?

**Comment by MarekChr** [comment]
Please provide all steps how you set up the container, what version of bridge you are usin, internal bridge settings and also what platform you are running on.

I set it up according to how-to steps in this repo and I am able to send anytime any number of emails on Debian 11.

**Comment by bahrthaare** [comment]
Hi thanks for the fast response. I'm using Debian 11.7 amd64. I figured it out.
I was sending a test mail with the same content and the proton-bridge is rejecting mails with the same content cause it is thinking it is the same mail. Obviously it isn't the same mail, just the same content. So it seems it is a "feature" of the proton-bridge and not related to the docker-image.

**Comment by MarekChr** [comment]
That is weird if it is the issue. I have been sending emails with same subject, recepient, from address and content and it was sent successfully. However I had atleast few seconds gap between.
